services:
    db.admin.group:
        class: DBBundle\Admin\GroupAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, label: "Группы" }
        arguments: [~, DBBundle\Entity\Group, ~]
        calls:
            - [ setTranslationDomain, [DBBundle]]
    
    db.admin.student:
        class: DBBundle\Admin\StudentAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, label: "Студенты" }
        arguments: [~, DBBundle\Entity\Student, ~]
        calls:
            - [ setTranslationDomain, [DBBundle]]
    db.admin.subject:
        class: DBBundle\Admin\SubjectAdmin
        tags:
            - {name: sonata.admin, manager_type: orm, label: "Предметы" }
        arguments: [~, DBBundle\Entity\Subject, ~]
        calls:
            - [ setTranslationDomain, [DBBundle]]
    db.admin.teacher:
            class: DBBundle\Admin\TeacherAdmin
            tags:
                - {name: sonata.admin, manager_type: orm, label: "Преподаватели" }
            arguments: [~, DBBundle\Entity\Teacher, ~]
            calls:
                - [ setTranslationDomain, [DBBundle]]
    db.admin.mark:
            class: DBBundle\Admin\MarkAdmin
            tags:
                - {name: sonata.admin, manager_type: orm, label: "Mark" }
            arguments: [~, DBBundle\Entity\Mark, ~]
            calls:
                - [ setTranslationDomain, [DBBundle]] 