imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  bundles_dir: '%kernel.root_dir%/../src'

framework:
    #esi:             ~
    default_locale: ru
    translator:
        fallbacks: [ru, en]
        paths:
            - "%bundles_dir%/DBBundle/Resources/translations"
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'DBBundle:form:marks_table.html.twig'
        - 'DBBundle:form:schedule_table.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
                    

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

    
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin_doctrine_orm.block.audit:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.rss:

#sonata_translation:
    #locales: [en, ru]
    #default_locale: ru
    #gedmo:
        #enabled: true
    #knplabs:
        #enabled: true
    #phpcr:
        #enabled: true
            
sonata_admin:
    title: AdminDB
    title_logo: /images/logo_green_cloud.png
    security:
        #handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            -
                class: col-lg-3
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Welcome to my AdminDB project</h2>
                        <h3>Get lucky here, and don't break anything =)</h3>
            -
                class: col-md-5
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [admin.group.main]

            -
                class: col-md-5
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [admin.group.db]
        groups:
            #admin.group.main:
                #label:  Main
                #label_catalogue: AppBundle
               # items:
                    #- app.admin.blogpost
                    #- app.admin.category
            admin.group.db:
                label: Lists
                label_catalogue: DBBundle
                items:
                    - db.admin.group
                    - db.admin.student
                    - db.admin.teacher
                    - db.admin.subject
                    #- db.admin.mark
            #admin.group.knp.lists:
                #label: Lists
                #label_catalogue: ~
                #items:
                    #- db.admin.student
                    #- db.admin.group
                    #- route: students_home
                    #  label: Some
                    #- route:        stedents_article
                    #  route_params: { articleId: 3 }
                    #  label:        Article


            #sonata.admin.groups.demo:
                #label: Demo
                #label_catalogue: DemoBundle
                #items:
                    #- sonata.demo.admin.car
    templates:
        layout: custom_standard_layout.html.twig
        edit: DBBundle:CRUD:edit.html.twig

sonata_doctrine_orm_admin:
        templates:
            types:
                list:
                    marktable: DBBundle:mark_table.html.twig